{application,ulti,
             [{description,"Ulti server"},
              {id,"ulti"},
              {vsn,"0.0.1"},
              {registered,[ulti_room_server]},
              {applications,[crypto,sasl,ranch,cowboy]},
              {mod,{ulti_app,[]}},
              {modules,[ulti_app,ulti_eval,ulti_http_handler,ulti_misc,
                        ulti_misc_test,ulti_play,ulti_player,ulti_room_server,
                        ulti_sup,ulti_ws_handler]}]}.
